# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0009_auto_20170326_1214'),
        ('core', '0007_auto_20170326_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disliked',
            field=models.ManyToManyField(related_name='dislikers', to='blogpost.Post'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked',
            field=models.ManyToManyField(related_name='likers', to='blogpost.Post'),
        ),
    ]
