# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170326_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='disliked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='liked',
        ),
    ]
