# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_blogs', to='blogpost.Post'),
        ),
    ]
