# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 18:40
from __future__ import unicode_literals

import blogpost.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_auto_20170312_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='title_post',
        ),
        migrations.AddField(
            model_name='blog',
            name='description_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.FileField(default='settings.MEDIA_ROOT/default_images/no_post_image.jpg', upload_to=blogpost.models.get_image_path),
        ),
        migrations.AddField(
            model_name='blog',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='settings.MEDIA_ROOT/default_images/no_post_image.jpg', upload_to=blogpost.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
