# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 19:22
from __future__ import unicode_literals

import blogpost.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_auto_20170312_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(default='/Users/Oskar/Desktop/Phystech/Technotrack/WEB/Project/media/default_images/no_post_image.jpg', upload_to=blogpost.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='/Users/Oskar/Desktop/Phystech/Technotrack/WEB/Project/media/default_images/no_post_image.jpg', upload_to=blogpost.models.get_image_path),
        ),
    ]
