# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0005_auto_20170312_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='noname blog', max_length=100),
        ),
    ]
