# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0007_auto_20170312_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='description_title',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='post',
            name='description_title',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default=' '),
        ),
    ]
