# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0009_auto_20170326_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('label-default', 'grey'), ('label-primary', 'blue'), ('label-success', 'green'), ('label-info', 'cyan'), ('label-warning', 'orange'), ('label-danger', 'red')], default='label-default', max_length=15),
        ),
    ]
