# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0011_auto_20170327_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description_title',
        ),
    ]
