# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0012_auto_20170327_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
